/*
 * This source file was generated by the Gradle 'init' task
 */
package mcd;

import mcd.config.DiscordConfig;

public class App {
    public static void main(String[] args) {
        Runtime.getRuntime().addShutdownHook(new Thread(DiscordConfig.getInstance()::shutdown));
    }
}
